### PR TITLE
Optional parameter for screenshot storing dir

### PR DESCRIPTION
**Pull request by ngocphamm**
It could be improved with directory exist checking, and/or more proper path combining

### CODE REVIEW

**Comment by duncan3dc** [comment]
Hi @ngocphamm, thanks for your contribution.
I'm not sure about it as it's not compatible with upstream, I think maybe we should accept either a fully qualified path or a single filename and then automatically add the temp path

**Comment by ngocphamm** [comment]
What do you mean it's not compatible with upstream? Sorry I just got into Dusk so I'm just new to this.

**Comment by duncan3dc** [comment]
The [laravel/dusk](https://github.com/laravel/dusk) project is "upstream". This library just wraps that one and attempts to provide the features it does, without you having to use Laravel.

The `screenshot()` method here is for compatibility with their `screenshot()` method. If we add a second parameter now, then they might add one in the future but use it differently to ours. That would making using this library confusing

**Comment by ngocphamm** [comment]
Oh I see what you are saying now. In the upstream, they have https://github.com/laravel/dusk/blob/3.0/src/Browser.php#L37, so maybe we can do the same?

**Comment by duncan3dc** [comment]
That's a bad idea because if you do:
```php
$google = new Dusk;
$google::$storeScreenshotsAt = "/tmp/google";
$google->visit("https://google.com/");

$bing = new Dusk;
$bing::$storeScreenshotsAt = "/tmp/bing";
$bing->visit("https://bing.com/");

$bing->screenshot("homepage");
$google->screenshot("homepage");
```
Then both screenshots would be saved to `/tmp/bing/homepage.png`, and the google one would overwrite the bing one

**Comment by ngocphamm** [comment]
Do you know if that only happens to this repo, or also with the upstream Dusk?

In this case, we can provide the relative paths to `screenshot()` method instead of trying to assign 2 different paths to `$storeScreenshotAt` like in your example. `screenshot('google/homepage.png')` and `screenshot('bing/homepage.png')`, and the underlying `getDriver()->takeScreenshot()` method doesn't care about the relative paths, as long as they exist, right?

**Comment by duncan3dc** [comment]
Yes it's a problem with upstream Dusk.

I think I'll go with the only adding the temp path to non-fully-qualified paths as mentioned earlier, let me take a look at it when I get a minute

**Comment by duncan3dc** [comment]
This is available in the [0.8.0](https://github.com/duncan3dc/dusk/releases/tag/0.8.0) release now:
```php
$dusk->screenshot("/home/ngocphamm/page1");
```

**Pull request closed without merging**
